config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new
  get 'tasks/:id', to: 'tasks#show', as: :show
  post 'tasks', to: 'tasks#create', as: :create

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update', as: :task

  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" style="margin: 0 auto;"></div>
      <%= yield %>
    </div>
    <script src="https://kit.fontawesome.com/2e3a6ec173.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>
<% if @task.completed %>
  <i class="far fa-check-square"></i>
<% else %>
  Mark as done ?
  <%= link_to task_path(@task, :params => {:task => {completed: true}}), method: 'patch' do %>
    <i class="far fa-square"></i>
  <% end %>
<% end %>
<p>
  <i class="fas fa-undo"></i> <%= link_to "Back to List", tasks_path %>
</p>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul>
  <% @tasks.each { |task| %>
  <li>
    <% if task.completed %>
        <%= link_to task_path(task.id, :params => {:task => {completed: false}}), method: 'patch' do %>
          <i class="far fa-check-square"></i>
        <% end %>
     <% else %>
        <%= link_to task_path(task.id, :params => {:task => {completed: true}}), method: 'patch' do %>
          <i class="far fa-square"></i>
        <% end %>
     <% end %>

    <%= link_to task.title, show_path(task) %>
        <%= link_to delete_path(task), method: 'delete', data: { confirm: "Are you sure?" } do %>
          <i class="far fa-trash-alt"></i>
        <% end %>

  </li>
  <% } %>
</ul>
<p>
    <i class="fas fa-plus"></i><%= link_to "Add a new Task", new_path %>
</p>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

<i class="fas fa-undo"></i> <%= link_to "Back to List", tasks_path %>

app/views/tasks/show.html.erb
<h1>Details Task</h1>

<h3> <%= @task.title %> </h3>
<p> <%= @task.details %> </p>
<p>
    <% if @task.completed %>
     <i class="far fa-check-square"></i> This task is completed !
     <% else %>
     <i class="far fa-square"></i> This Task in not completed yet
     <% end %>
   </p>

<i class="fas fa-undo"></i> <%= link_to "Back to List", tasks_path %>

<p>
  Edit this task ?
<%= link_to edit_path do%>
<i class="fas fa-pen"></i>
<% end %>
</p>